inference:
  pdb_path: null #Path to the input PDB
  json_file: null #Path to the input JSON file
  seed: 0 #Set seed for torch, numpy, and python random
  temperature: 0.1 #Temperature to sample sequences
  out_folder: outputs/ #Path to a folder to output sequences, e.g. /home/out/
  model_type: ligand_mpnn #Choose your model: protein_mpnn, ligand_mpnn, per_residue_label_membrane_mpnn, global_label_membrane_mpnn, soluble_mpnn
  batch_size: 1 #Number of sequence to generate per one pass
  number_of_batches: 1 #Number of times to design sequence using a chosen batch size
  verbose: 0 #1 - to print more information, 0 - to print less information
  save_stats: False
  zero_indexed: 0 #1 - to start output PDB numbering with 0
  force_hetatm: 0 #To force ligand atoms to be written as HETATM to PDB file after packing
  
  bias_AA: null #Bias generation of amino acids, e.g. 'A:-1.024,P:2.34,C:-12.34
  bias_AA_per_residue: null #Path to json mapping of bias {'A12': {'G': -0.3, 'C': -2.0, 'H': 0.8}, 'A13': {'G': -1.3}}
  bias_AA_per_residue_multi: null #Path to json mapping of bias {'pdb_path': {'A12': {'G': -0.3, 'C': -2.0, 'H': 0.8}, 'A13': {'G': -1.3}}}
  transmembrane_buried: null #Provide buried residues when using checkpoint_per_residue_label_membrane_mpnn model, A12 A13 A14 B2 B25
  transmembrane_interface: null #Provide interface residues when using checkpoint_per_residue_label_membrane_mpnn model, A12 A13 A14 B2 B25
  global_transmembrane_label: 0 #Provide global label for global_label_membrane_mpnn model. 1 - transmembrane, 0 - soluble

  #provide these only if no JSON file is provided above
  fixed_residues: null #Provide fixed residues, A12 A13 A14 B2 B25
  redesigned_residues: null #Provide to be redesigned residues, everything else will be fixed, A12 A13 A14 B2 B25
  pdb_path_multi: null #Path to json listing PDB paths. {'/path/to/pdb': ''} - only keys will be used.
  fixed_residues_multi: null #Path to json mapping of fixed residues for each pdb i.e., {'/path/to/pdb': 'A12 A13 A14 B2 B25'}
  redesigned_residues_multi: null #Path to json mapping of redesigned residues for each pdb i.e., {'/path/to/pdb': 'A12 A13 A14 B2 B25'}
  chains_to_design: null #Specify which chains to redesign, all others will be kept fixed
  homo_oligomer: 0 #Setting this to 1 will automatically set --symmetry_residues and --symmetry_weights to do homooligomer design with equal weighting.
  symmetry_residues: null #Add list of lists for which residues need to be symmetric, e.g. 'A12,A13,A14|C2,C3|A5,B6'
  symmetry_weights: null #Add weights that match symmetry_residues, e.g. '1.01,1.0,1.0|-1.0,2.0|2.0,2.3'    
  omit_AA: null #Bias generation of amino acids, e.g. 'ACG'
  omit_AA_per_residue: null #Path to json mapping of bias {'A12': 'APQ', 'A13': 'QST'
  omit_AA_per_residue_multi: null #Path to json mapping of bias {'pdb_path': {'A12': 'QSPC', 'A13': 'AGE'}}

  
  pack_side_chains: 0 #1 - to run side chain packer, 0 - do not run it
  number_of_packs_per_design: 4 #Number of independent side chain packing samples to return per design
  pack_with_ligand_context: 0 #1-pack side chains using ligand context, 0 - do not use it
  ligand_mpnn_use_side_chain_context: 0 #Flag to use side chain atoms as ligand context for the fixed residues
  repack_everything: 0 #1 - repacks side chains of all residues including the fixed ones; 0 - keeps the side chains fixed for fixed residues
  sc_num_denoising_steps: 3 #Number of denoising/recycling steps to make for side chain packing
  sc_num_samples: 16 #Number of samples to draw from a mixture distribution and then take a sample with the highest likelihood
  parse_these_chains_only: null #Provide chains letters for parsing backbones, 'ABCF'
  parse_atoms_with_zero_occupancy: 0 #To parse atoms with zero occupancy in the PDB input files. 0 - do not parse, 1 - parse atoms with zero occupancy
  ligand_mpnn_cutoff_for_score: 8.0 #Cutoff in angstroms between protein and context atoms to select residues for reporting score
  ligand_mpnn_use_atom_context: 0 #1 - use atom context, 0 - do not use atom context

  fasta_seq_separation: "," #Symbol to use between sequences from different chains
  file_ending: null
  packed_suffix: _packed #Suffix for packed PDB paths


checkpoint_path_sc: /proj/kuhl_lab/LigandMPNN/model_params/ligandmpnn_sc_v_32_002_16.pt
checkpoint_protein_mpnn: /proj/kuhl_lab/LigandMPNN/model_params/proteinmpnn_v_48_020.pt
checkpoint_ligand_mpnn: /proj/kuhl_lab/LigandMPNN/model_params/ligandmpnn_v_32_010_25.pt
checkpoint_per_residue_label_membrane_mpnn: /proj/kuhl_lab/LigandMPNN/model_params/per_residue_label_membrane_mpnn_v_48_020.pt
checkpoint_global_label_membrane_mpnn: /proj/kuhl_lab/LigandMPNN/model_params/global_label_membrane_mpnn_v_48_020.pt
checkpoint_soluble_mpnn: /proj/kuhl_lab/LigandMPNN/model_params/solublempnn_v_48_020.pt
