flags:
  run_dir: ./
  num_gpus: 1
  num_iter: 3
  
  pool_size: 4
  pool_size_variable: False  #set one of the two options below if True
  pool_sizes_file: null
  pool_sizes: null
  
  mutation_percents: 0.125
  crossover_percent: 0 #TODO add crossover
  single_mut_only: False
  residue_specs_file: ./residue_specs.json
  starting_seqs_file: null

  no_plots_output: False
  plot_scores: average
  num_repeat_scoring: 5
  dont_write_compressed_data: False
  write_all_pdbs: False

structure_prediction:
  structure_pred_chains: AB,A
  structure_prediction_tool: af2
  structure_prediction_tool_location: /proj/kuhl_lab/alphafold/run/d
  custom_msa_chains: null #set these only with af3
  custom_msa_paths: null
  custom_template_chains: null
  custom_template_paths: null
  #/proj/kuhl_lab/RosettaFold2/RoseTTAFold2/run/
  seed: 42
  structure_pred_flags_file: ./af2.flags

sequence_prediction:
  sequence_pred_chains: AB
  sequence_prediction_tool_location: /proj/kuhl_lab/LigandMPNN/
  sequence_prediction_tool_conf: ./mpnn_evopro.yaml
  mpnn_version: s_48_020
  mpnn_freq: 2 #run mpnn every other iteration
  mpnn_iters: null #overwridden by mpnn_freq. set this only if mpnn_freq is null
  skip_mpnn: null #skip mpnn on these specific iterations
  mpnn_temp: 0.1
  mpnn_temp_variable: False
  
  bias_AA: null
  bias_by_res: null
  
scoring:
  plddt:
    score_plddt: True
    preds: AB,A #which predictions to calculate score on
    residues: A1-A40
    weights: -1,-1 #weight for scores calculated for each prediction

  ptm:
    score_ptm: False
    preds: AB
    weights: -1

  iptm:
    score_iptm: True
    preds: AB
    weights: -1

  contacts:
    score_contacts: True
    preds: AB
    interface_1: B* #target interface
    interface_2: A* #binder interface
    weights: -1

    max_contacts: 50
    contact_distance: 4 #Angstroms, all atom calculation
    
    bonus_residues: B34 #residues on the target that the binder should contact
    bonus_distance: 4
    bonus_weight: 5
    penalty_residues: B6 #residues on the target that the binder should NOT contact
    penalty_distance: 8
    penalty_weight: 5

  conf_change:
    score_conf_change: True
    preds: AB,A #preds between which to calculate the score
    residues: A*
    weights: 1

  rmsd:
    score_rmsd: False
    preds: AB
    rmsd_pdb: ./design.pdb
    residues: null
    weights: 1

  
  hbond: #TODO
    score_hbond: False
    preds: AB
    residues: A*
    weights: 1

    
  custom:
    score_custom: False
    preds: AB
    custom_script: null
    custom_score_func: null
    weights: 1